/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtonGroup: typeof import('./src/components/common/ActionButtonGroup.vue')['default']
    AppBreadcrumb: typeof import('./src/components/layout/AppBreadcrumb.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppLogo: typeof import('./src/components/layout/AppLogo.vue')['default']
    AppMenu: typeof import('./src/components/layout/AppMenu.vue')['default']
    AppPagination: typeof import('./src/components/common/AppPagination.vue')['default']
    AppTopBar: typeof import('./src/components/layout/AppTopBar.vue')['default']
    AppWorkTab: typeof import('./src/components/layout/AppWorkTab.vue')['default']
    GlobalSearch: typeof import('./src/components/common/GlobalSearch.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/LayoutHeader.vue')['default']
    LayoutSidebar: typeof import('./src/components/layout/LayoutSidebar.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleForm: typeof import('./src/components/common/SimpleForm.vue')['default']
    SimpleSearch: typeof import('./src/components/common/SimpleSearch.vue')['default']
  }
}
